### ISSUE TITLE
Merge request with my autosuspend

### ISSUE THREAD

**Issue by languitar** [git-developer/autosuspend#10]
You have sent me an email about merging your features into my implementation of autosuspend. Unfortunately, your mail server doesn't know your user name, so I cannot reply via mail ;-)

**Comment by languitar** [comment]
Geht immer noch nicht ;-) Recipient address rejected: User unknown (in reply to RCPT TO command) (in reply to RCPT TO command)

**Comment by git-developer** [comment]
Hmm... die Adresse habe ich inzwischen von unterschiedlichen Stellen aus getestet, sie sollte funktionieren. Ich habe Dir um 17:29 geantwortet und gerade eben folgende Antwort erhalten (Deine E-Mail-Daten sind habe ich unkenntlich gemacht):
```
This is the mail system at host xxxxxxx.xx.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<xxxxxxxxx@xxxxxxx.xx>: Command time limit exceeded: "/usr/bin/spamc"
```
Ist evtl. mein Mailserver bei Deinem nicht willkommen?

**Comment by languitar** [comment]
Sorry, da war ich gerade an meinem Server zu Gange ;)
