### ISSUE TITLE
Add support for URLs to the Tvheadend REST API containing a context path

### ISSUE THREAD

**Issue by git-developer** [git-developer/autosuspend#12]
Feature request of user @CV8R from issue #11:

I changed the webroot per these instructions by modifying `/etc/default/tvheadend`

https://tvheadend.org/boards/4/topics/10626

When i change the curl to:

`sudo curl -s --user "username:password" "http://127.0.0.1:9981/tvh/api/dvr/entry/grid_upcoming?sort=start_real&dir=ASC&limit=5" >response.js`

Data is returned as expected.

I took a brief look at the config file for autosuspend and it looks like it only has config for IP Address and Port instead of a URL and assumed it's probably appending the two.

I appended `/tvh` to the port value

`TVHEADEND_HTTP_PORT=9981/tvh`

On quick tests using the `test-autosuspend-function.sh` it is returning correct values. I have set autosuspend to sleep the machine again and will see how it goes and shall report back.

Ideally there would be a config item for changing the URL.

**Comment by CV8R** [comment]
Hi, made the changes and it is working as expected.  Machine sleeps, I can see the syslog entries for the next event, I can see suspend caused and it wakes at the prescribed time.

Fantastic - thank you!

Feedback on the comment in the config file. At first I added

`http://$TVHEADEND_IP:$TVHEADEND_HTTP_PORT/tvh`

Wondering if it picked it up from hostname and default port, found that it didn't work and then changed to. I think the $ confused me, so there was some guess work.

`TVHEADEND_HTTP_URL=http://127.0.0.1:9981/tvh`

Only minor observation - it's is beautiful thing!

Cheers
CV8R
