### ISSUE TITLE
some users still connected

### ISSUE THREAD

**Issue by nebosa** [git-developer/autosuspend#2]
Hello,
which means: some users still connected ?

 `autosuspend[10285]: some users still connected, auto suspend terminated
`

Can I display the reason (users still connected) ? As ?
Can I create my own log file for suspend?
sorry for my goole english :)

**Comment by git-developer** [comment]
This message occurs when a user is connected to the machine. You can manually check who is logged in by calling `who`, either from a shell or by changing the [autosuspend script](https://github.com/git-developer/autosuspend/blob/ddd79520decddb5b355518d15790cb403338d442/usr/local/sbin/autosuspend.sh#L71). You can also extend the logging there.

**Comment by nebosa** [comment]
Thank you.
User I can solve. Here it is not enough to go with the client in standy. I have to log out beforehand in the terminal.
At the log I need help.
I would like a log file:
autosuspend.log
Can they tell me what I have to do?

**Comment by git-developer** [comment]
`autosuspend` sends its log messages to the syslog daemon, so you just have to tell syslog to put all autosuspend messages into a separate file. How exactly to achieve this depends on your configuration. Here is an example if you're using the default Debian / Ubuntu daemon called `rsyslog`:
- Create a new rsyslog configuration file for autosuspend: `/etc/rsyslog.d/autosuspend.conf`
- Edit the file and enter the following 2 lines:
```
:programname, isequal, "autosuspend" /var/log/autosuspend.log
& stop
```
- Restart the rsyslog daemon: `sudo service rsyslog restart`

The exact syntax may differ depending on your rsyslog version, but you can find a lot of resources on the web, e.g. [Filter log messages by program name and log level at the same time in rsyslogd](https://serverfault.com/questions/230120/filter-log-messages-by-program-name-and-log-level-at-the-same-time-in-rsyslogd)

**Comment by nebosa** [comment]
Perfect! Many Thanks
