### ISSUE TITLE
Do not sleep in case rtcwake fails

### ISSUE THREAD

**Issue by orgi** [git-developer/autosuspend#20]
As a fallback it would be great to abort the sleep in case there's no wake time set. (E.g. because of issues like #19).

I think in general in most cases this will be no use-case as the only way to recover from that will be a manual power-on.

**Comment by orgi** [comment]
Just saw in your current code that this may be already addressed...

**Comment by git-developer** [comment]
This feature is implemented by commit [4449202](https://github.com/git-developer/autosuspend/commit/4449202ca6e58e5fd64c1dbc50809063990e9027) since 2017-10-30. Please check if an update of autosuspend resolves your problem and report back.

**Comment by orgi** [comment]
Thanks for the quick answer. The update indeed seems to resolve the issue. :)
