### ISSUE TITLE
Next recordings are not fetched

### ISSUE THREAD

**Issue by orgi** [git-developer/autosuspend#21]
After updating to the latest scripts (commit 1569433) autosuspend does no longer fetch my scheduled recordings resulting in not suspending at all.

After some analysis I came across the following line:
https://github.com/git-developer/autosuspend/blob/e7f340d24996c61e0cb9f725127cd4ac93a47f9e/usr/local/sbin/autosuspend.tvheadend-functions#L120

If I change it to
```
    if [ "$?" != 0 ]; then
```
it seems to work.

But I am not sure whether this is the right fix to do, as if it would, this presumably never could have worked, could it? :confused:

**Comment by git-developer** [comment]
Well spotted!

The error has been introduced shortly (2020-05-18) with commit [e7f340d](https://github.com/git-developer/autosuspend/commit/fc9a4e61e92749d41c6f05ffd179464664a9d3c0#diff-8fdea9d96a17d8d086bac417fa378ff8R120). I didn't notice that in the review.

I just committed your suggestion as fix, thanks!
