### ISSUE TITLE
Implement Digest Authentication

### ISSUE THREAD

**Issue by CV8R** [git-developer/autosuspend#24]
Just upgraded to tvheadend v4.3 and ran into authentication issues.  Found I needed to change to digest+plain authentication.  Would be nice to remove the dependency on plain and have digest implemented.

**Comment by git-developer** [comment]
Thanks for your feedback.

Please check if branch `feature/auth-digest` meets your requirement. In this branch, autosuspends supports a new configuration variable `TVHEADEND_CURL_OPTIONS` for custom curl options. You could try the following line in your configuration: 

```TVHEADEND_CURL_OPTIONS=--digest```

**Comment by git-developer** [comment]
I'm looking forward to your feedback, @CV8R.

**Comment by CV8R** [comment]
@git-developer I'll feedback for sure.  Unfortunately the day job has got in the way so won't be able to look at it for a few of days.

**Comment by git-developer** [comment]
Any updates, @CV8R?

**Comment by CV8R** [comment]
Hi @git-developer, apologies for the delay. I had the chance to install it yesterday.  It appears to be working but its a bit too early to confirm.  Is there a test I can run to ensure that it is logging in and reading the guide?

**Comment by git-developer** [comment]
You could schedule a record that starts within the next `TVHEADEND_IDLE_MINUTES_BEFORE_RECORDING` minutes, logoff and watch of the server is shutting down.

**Comment by CV8R** [comment]
Looks like its working. I can see the Next activity in the syslog. It is sleeping, not sleeping during records and waking.  Sorted - thank you!

**Comment by git-developer** [comment]
You're welcome!
