### ISSUE TITLE
Which config file for timestamp to wake up at a certain time ? 

### ISSUE THREAD

**Issue by malvinas2** [git-developer/autosuspend#3]
Does the script use the config file within `/etc/autosuspend.d/activities` to set a timestamps for preparing the next wake up or does it still use `/etc/autosuspend_resumeplan` as the original AutoSuspend from /wiki.ubuntuusers.de does ? 

The documentation just mentions the 'activities'-file, but within the source code the only reference I can find is /etc/autosuspend_resumeplan (line 105 and 110).

**Comment by git-developer** [comment]
The script prefers the activities files under `/etc/autosuspend.d/activities`.

First, autosuspend [checks if the machine is busy](https://github.com/git-developer/autosuspend/blob/ddd79520decddb5b355518d15790cb403338d442/usr/local/sbin/autosuspend.sh#L97) (e.g. running applications, connected users, Tvheadend activity). If so, the [wakeup time is set](https://github.com/git-developer/autosuspend/blob/ddd79520decddb5b355518d15790cb403338d442/usr/local/sbin/autosuspend.tvheadend-functions#L131) considering [Tvheadend schedules](https://github.com/git-developer/autosuspend/blob/ddd79520decddb5b355518d15790cb403338d442/usr/local/sbin/autosuspend.tvheadend-functions#L87) and [the files within `/etc/autosuspend/activities.d`](https://github.com/git-developer/autosuspend/blob/ddd79520decddb5b355518d15790cb403338d442/usr/local/sbin/autosuspend.tvheadend-functions#L92).

The original resumeplan mechanism is used as fallback if
1. there are no recordings planned
1. *and* there is no user activity in `/etc/autosuspend/activities.d`
1. *and* `/etc/autosuspend_resumeplan` exists
