### ISSUE TITLE
Shutdown works but recording dont wake up

### ISSUE THREAD

**Issue by hackbird001** [git-developer/autosuspend#6]
Hey,

i installed your script on debian 8. 
Shutdown and wake up over WOL with this script no problem.
But only when i make an cronjob......

I installed TVH on my server and script wont wake up.
I use TVH 4.3

**Comment by git-developer** [comment]
Have you set your credentials in the autosuspend configuration file? Are there scheduled recordings? The autosuspend script logs to your system log (`/var/log/syslog`), have a look into it to see what happens.

**Comment by hackbird001** [comment]
Hello,
i test it both ways. First i was runnning without an user. I run TVH with the admin and pass was i set on installing. These i write in autosuspend. Script wont start. Then i set an user with all rights and write this in autosuspend. Script wont start.
I use OMV on my server an the syslog says all the time when i set an recording that it is sheduled for recording. After 15 Minutes the server goes in suspend. Then i wait that he wakes up for recording but nothing happend. When i WOL then recording starts when it is back online.

The only thing what i dont understand is, when i write in terminal:

#/usr/local/sbin/autosuspend.sh

Then it comes this:  AutoSuspend: Missing Tvheadend credentials (user and/or password)

I dont know why, because i set user and password????

**Comment by git-developer** [comment]
This message means that username and/or password are not set in the autosuspend configuration as described [here](https://github.com/git-developer/autosuspend#configuration). Could you please double-check that your credentials are set (without leading `#`) in the autosuspend configuration file `/etc/autosuspend`?

I can better help if you post your configuration file and the system log here.

**Comment by hackbird001** [comment]
Hey, 
here are my syslog and my autosuspend with the actually configuration
[autosuspend.txt](https://github.com/git-developer/autosuspend/files/1444101/autosuspend.txt)
[syslog.txt](https://github.com/git-developer/autosuspend/files/1444102/syslog.txt)

**Comment by hackbird001** [comment]
I found the failure.
On the credentials i thought on the beginning the " # " must be set.
Now i remove this and now it works.

Sorry but it will be good, that u write this in ur "Readme".

Thx for helpinf
