### ISSUE TITLE
No wake up time scheduled

### ISSUE THREAD

**Issue by hackbird001** [git-developer/autosuspend#7]
Hello Stefan,

me again. I got problems that system wake up for recording.
I show you my config of my autosuspend in the txt file.

When i programmed on TVH an recording it shows me that it is sheduled. 
Before NAS goes in suspend it shows me:
"No wake up time scheduled" 
"Activity scripts may be added to '/etc/autosuspend.d/activities"

Which and how script must i write?? Hope u can help me again?

[autosuspend.txt](https://github.com/git-developer/autosuspend/files/1444498/autosuspend.txt)
[syslog.txt](https://github.com/git-developer/autosuspend/files/1444503/syslog.txt)

**Comment by git-developer** [comment]
Looks like the autosuspend script doesn't find any scheduled recordings. Please have a look at [my answer](https://github.com/git-developer/autosuspend/issues/1#issuecomment-273273158) to issue #1. Please run `curl` as described there so we can check the answer from Tvheadend.

**Comment by hackbird001** [comment]
Hey,

when i use this command:
curl -s --user "$TVHEADEND_USER:$TVHEADEND_PASSWORD" "http://ada:9981/api/dvr/entry/grid_upcoming?sort=start_real&dir=ASC&limit=5" >response.json

and check after the response.json file it is empty.
Nothing inside

Here my syslog:

[syslog.txt](https://github.com/git-developer/autosuspend/files/1445989/syslog.txt)

**Comment by git-developer** [comment]
You have to replace `$TVHEADEND_USER:$TVHEADEND_PASSWORD` with you credentials, e.g.`hackbird:hackbird`.

**Comment by hackbird001** [comment]
Hat leider auch nicht geholfen.
Habs so eingetragen und anders nochmal.Schreibt aber nichts ins file.
curl -s --user "hackbird:hackbird" "http://ada:9981/api/dvr/entry/grid_upcoming?sort=start_real&dir=ASC&limit=5" >response.json

curl -s --user "$hackbird:$hackbird" "http://ada:9981/api/dvr/entry/grid_upcoming?sort=start_real&dir=ASC&limit=5" >response.json

**Comment by git-developer** [comment]
When I read your system log correctly, your hostname is not `ada` but `AdlersHorst`, so your command would be
`curl -s --user "hackbird:hackbird" "http://AdlersHorst:9981/api/dvr/entry/grid_upcoming?sort=start_real&dir=ASC&limit=5" >response.json`

**Comment by hackbird001** [comment]
Sorry, for the mistake. Didnt see
So now the result of the Log:

[response.txt](https://github.com/git-developer/autosuspend/files/1446992/response.txt)

**Comment by git-developer** [comment]
The given user is not authorized to request your schedule. Please check the permissions in the Tvheadend UI.

**Comment by hackbird001** [comment]
Ok understand.
I use only my admin account. I didnt set an extra User.
So with this script it is requirements to create an User??
When not where can i set the permission?

**Comment by hackbird001** [comment]
I set the admin account in autosuspend but it always says not authorized.
I restart and and and no chance.
Where can i look into the permission for admin?
At the moment i use the HTS Tvheadend 4.2.4-10~g0771e34

**Comment by git-developer** [comment]
The admin user should have all necessary permissions. Are you sure that the password is correct?

If you want to try a dedicated user account, the documentation is here: [Access Configuration](https://www.tvheadend.org/projects/tvheadend/wiki/Access_configuration).

**Comment by git-developer** [comment]
Is it possible that you're mixing up your Tvheadend account with your linux system account? The autosuspend script is using a Tvheadend account.

**Comment by hackbird001** [comment]
To create an other user wasn´t successfully.
Always same 401...
I install TVHeadend on OpenMediaVault3 which works on debian8. This is my server software. 
The Suspend Script works.
It goes in standby and wake up with WOL..
The only thing wont work is to wake up on shedulled programm

**Comment by git-developer** [comment]
I tried to reproduce your problem. It happens only when username and/or password is not correct.

When you're able to login to Tvheadend with your credentials in a browser, the autosuspend script will also be able to use these credentials to request your schedule.

I created a new user account in Tvheadend 4.2:
![grafik](https://user-images.githubusercontent.com/7452817/32459633-9a8cf7f4-c330-11e7-950f-84a95270d9a6.png)
- Username: `autosupend`
- Password: `autosuspend`
- Web interface: checked
- Admin: checked
- Video recorder: Basic, Failed View

The command

```curl -s --user "autosuspend:autosuspend" "http://localhost:9981/api/dvr/entry/grid_upcoming?sort=start_real&dir=ASC&limit=5"```

does not result in error 401 but in a JSON file staring with `{"entries"`.

**Comment by hackbird001** [comment]
I describe what i done.
I install OMV3 which is on debian 8 jessie.
After i install TVHeadend from here:
https://dl.bintray.com/tvheadend/deb/pool/4.2/tvheadend/
Version: 4.2.4-10~g0771e34

In installation i set the superuser:Pass for login in TVH
Installation of my DVBC 
This was all. 

My Pics looks so without users:

![unbenannt](https://user-images.githubusercontent.com/25282182/32461032-dd088202-c334-11e7-841e-9cfe88ca3bc9.png)

**Comment by git-developer** [comment]
Tvheadend requires at least one user with the appropriate rights if you want to request the schedule. In my installation, the Tvheadend setup created a user `admin` with full rights by default.
Your problem should be solved if you add a user and configure it as shown on the screenshot.

**Comment by hackbird001** [comment]
Ok, perfect.
This works now for me.
Dont know why it not set on Users "admin" on install.
But now it works. I programm now one thing and i report you here if it works.
So let it open till tomorrow and i write here if it works.
THX for helping

**Comment by hackbird001** [comment]
Ok, its working now... 
:-)))))))
